# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ax5QfjDLsIh9vLmKe8AJilIFU5RD3k33
"""

import os
os.environ['KAGGLE_USERNAME'] ='priya'
os.environ['KAGGLE_KEY'] = 'KGAT_445f66f5ad730e867873287ea42987b7'

!pip install kaggle

!kaggle datasets download -d 'yasserh/titanic-dataset'

import pandas as pd
df=pd.read_csv('titanic-dataset.zip')
df.head(10)

df.tail(10)

print(len(df))

print(df.shape)

df.info()

df.duplicated().sum()

df.dtypes

df.shape

df.drop_duplicates(inplace=True)
print(df)

df.isnull()

df.isnull().sum()

df['Age'] = df['Age'].fillna(df['Age'].median())
print(df[['Age']].head(10))
print(df.isnull().sum())

df['Sex']=df['Sex'].astype('category')
df['Sex']=df['Sex'].cat.codes
print(df[['Sex']].head(10))

print(df.columns)

df.drop('Fare', axis=1, inplace=True)
print(df)

df['HasCabin'] = df['Cabin'].notnull().astype('int')
df.drop('Cabin', axis=1, inplace=True)

df['Sex']=df['Sex'].map({0:'male',1:'female'})
print(df[['Sex']])

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
print(df[['FamilySize']])

import matplotlib.pyplot as plt
plt.boxplot(df['Pclass'])
plt.title('Outlier detection using Boxplot')
plt.ylabel('Fare')
plt.show()

X = df.drop('Survived', axis=1)
y = df['Survived']

X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))



