# -*- coding: utf-8 -*-
"""netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2hA88jUFm1Hec-PkPfFsx7uagQOUDFk
"""

import os
os.environ['KAGGLE_USERNAME'] ='priya'
os.environ['KAGGLE_KEY'] = 'KGAT_445f66f5ad730e867873287ea42987b7'

!kaggle datasets download -d 'shivamb/netflix-shows'

import pandas as pd
df=pd.read_csv('netflix-shows.zip')
df.head(10)

df.tail(10)

print(len(df))

print("Rows and Columns:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Info:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

print(df.isnull().sum()) # missing value

df["director"] = df["director"].fillna("Unknown")

df["cast"] = df["cast"].fillna("Unknown")

df["country"] = df["country"].fillna(df["country"].mode()[0])

df["rating"] = df["rating"].fillna(df["rating"].mode()[0])

df.dropna(inplace=True)
print(df.isnull().sum())

print("Duplicate Rows:", df.duplicated().sum())
df.drop_duplicates(inplace=True)

print(df.columns)

df.drop(["show_id", "description"], axis=1, inplace=True)      #drop
print(df.head())

df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")
df["year_added"] = df["date_added"].dt.year                                   # add coloum
df["month_added"] = df["date_added"].dt.month

print(df.head())

from sklearn.preprocessing import LabelEncoder
# Remove date column (already extracted year and month)
df.drop("date_added", axis=1, inplace=True)
# Convert all text columns to numeric
df = pd.get_dummies(df, drop_first=True)

print(df.head())

X = df[["release_year", "year_added", "month_added"]]
y = df["type_TV Show"]

print(X.isnull().sum().sum())

X = X.fillna(0)

print(X.isnull().sum().sum())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(df.isnull().sum())

import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
plt.plot([accuracy], marker='o')
plt.ylabel("Accuracy")
plt.title("Model Accuracy")
plt.show()