# -*- coding: utf-8 -*-
"""studentperformance ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCy1Dwbq2p_pNtWjlBR0n-IQD1F2xCO-
"""

import os
os.environ['KAGGLE_USERNAME'] ='priya'
os.environ['KAGGLE_KEY'] = 'KGAT_445f66f5ad730e867873287ea42987b7'

!kaggle datasets download -d 'kundanbedmutha/student-performance-dataset'

import pandas as pd
df=pd.read_csv('student-performance-dataset.zip')
df.head(10)

df.tail(10)

print(len(df))

print("Rows and Columns:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Info:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

print(df.isnull().sum()) # missing value

print("Duplicate Rows:", df.duplicated().sum())
df.drop_duplicates(inplace=True)

df.drop(["student_id"], axis=1, inplace=True)
print(df.head())

df["attendance_category"] = pd.cut(
    df["attendance_percentage"],
    bins=[0, 75, 90, 100],                 # add colum
    labels=["Low", "Medium", "High"]
)
print(df.head())

print(df.columns)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["final_grade"] = le.fit_transform(df["final_grade"])

df = pd.get_dummies(df, drop_first=True)

print(df.head())

X = df.drop("final_grade", axis=1)

y = df["final_grade"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred[:5])

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

import matplotlib.pyplot as plt
import seaborn as sns
sns.countplot(x="final_grade", data=df)
plt.title("Final Grade Distribution")
plt.show()